// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	User
	CreateRequest
	CreateResponse
	GetRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id             int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	HashedPassword string `protobuf:"bytes,3,opt,name=hashedPassword" json:"hashedPassword,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

type CreateRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRequest struct {
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*User)(nil), "proto.User")
	proto1.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto1.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/proto.UserService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/proto.UserService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*User, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto1.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4f, 0x85, 0x30,
	0x10, 0xc7, 0x5f, 0xe1, 0xf9, 0xa2, 0x87, 0x92, 0x78, 0xd1, 0x84, 0x30, 0x91, 0x0e, 0xfa, 0x26,
	0x06, 0x1d, 0x1c, 0x1d, 0x1c, 0x58, 0x4d, 0x8d, 0x1f, 0xa0, 0xda, 0x4b, 0x60, 0x90, 0x62, 0xaf,
	0xe8, 0xd7, 0x37, 0xb4, 0x80, 0xca, 0xd4, 0xde, 0xff, 0x72, 0xbf, 0xdf, 0x1d, 0x64, 0x23, 0x93,
	0xe3, 0x7a, 0x70, 0xd6, 0x5b, 0x3c, 0x09, 0x8f, 0x54, 0xb0, 0x7f, 0x65, 0x72, 0x98, 0x43, 0xd2,
	0x99, 0x42, 0x54, 0xe2, 0x98, 0xaa, 0xa4, 0x33, 0x88, 0xb0, 0xef, 0xf5, 0x07, 0x15, 0x49, 0x25,
	0x8e, 0x67, 0x2a, 0xfc, 0xf1, 0x06, 0xf2, 0x56, 0x73, 0x4b, 0xe6, 0x59, 0x33, 0x7f, 0x5b, 0x67,
	0x8a, 0x34, 0x74, 0x37, 0xa9, 0x7c, 0x84, 0x8b, 0x27, 0x47, 0xda, 0x93, 0xa2, 0xcf, 0x91, 0xd8,
	0xaf, 0x30, 0xf1, 0x07, 0x56, 0xc2, 0xe9, 0xb0, 0x60, 0xa2, 0x64, 0xad, 0x65, 0x05, 0xf9, 0x02,
	0xe0, 0xc1, 0xf6, 0x4c, 0xdb, 0xf5, 0xe4, 0x39, 0x40, 0x43, 0x7e, 0xe6, 0xdf, 0x59, 0xc8, 0xa6,
	0x23, 0x5e, 0xc8, 0x7d, 0x75, 0xef, 0x84, 0x0f, 0x70, 0x88, 0xe3, 0x78, 0x15, 0x8f, 0xad, 0xff,
	0xad, 0x53, 0x5e, 0x6f, 0xd2, 0xe8, 0x90, 0x3b, 0xbc, 0x85, 0xb4, 0x21, 0x8f, 0x97, 0x73, 0xff,
	0xd7, 0x50, 0x66, 0x73, 0x34, 0x69, 0xe4, 0xee, 0xed, 0x10, 0xaa, 0xfb, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2c, 0x18, 0xb2, 0xfd, 0x52, 0x01, 0x00, 0x00,
}
